version: "3.7"
services:
  meter-go:
    image: spx01/meterng:amd64
    environment:
      - METER_DB.URL=host=db port=5432 user=meter dbname=meter password=meter sslmode=disable
      - METER_DB.DIALECT=postgres
      - METER_CONFIG.METERS=Wasser (m³), Gas (m³), Strom (kWh)
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=meter
      - POSTGRES_USER=meter
      - POSTGRES_PASSWORD=meter
