name: CI Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @ionic/cli
      - run: npm install @ionic/angular@latest --save
      - run: npm install -g @angular/cli

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
        id: go

      - name: Build
        run: make all

      - name: Check GoReleaser configuration
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check