name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v1
    - name: Build the Docker image and push
      run: |
        mkdir -p ~/.docker && echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        make testBackend
        make buildDockerImages
        make dockerManifestAndPush
        
        
