name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Docker login
    - uses: uses = "actions/docker/login@master"
      secrets = ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        make testBackend
        make buildDockerImages
        
        
